spring.application.name=sgd_hc
spring.config.import=optional:file:.env[.properties]

# ===================================================================
# 0. SERVER
# ===================================================================
server.port=${PORT:8080}

# ===================================================================
# 1. CONFIGURACIÓN BASE DE DATOS
# ===================================================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sgd_hc}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===================================================================
# 2. JPA / HIBERNATE
# ===================================================================
# IMPORTANTE: usar 'none' con Flyway
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# 3. FLYWAY (Migraciones de Base de Datos)
# ===================================================================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-version=0
spring.flyway.validate-on-migrate=false

# ===================================================================
# 4. JWT & SEGURIDAD
# ===================================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,https://calm-wave-000d39410.7.azurestaticapps.net}
logging.level.org.springframework.security=TRACE

# ===================================================================
# 5. OPENAPI / SWAGGER & OTROS
# ===================================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.show-actuator=true

# H2 Console (Opcional, solo si usas H2 en algún momento para pruebas)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console